"""AI Advisor page — gated, runtime-toggleable.

Registered by ``app.py`` ONLY when ``ai_advisor.enabled`` is true AND the sidebar
"AI insights" toggle is on. Shows a deterministic gap analysis (always factual) plus
a Claude-generated narrative, behind an always-visible "not investment advice"
disclaimer. The Claude call is cached in session state (Refresh button to re-run).
"""

from __future__ import annotations

import streamlit as st

from advisor import DISCLAIMER
from advisor import analysis as advisor_analysis
from advisor import llm as advisor_llm
from advisor.profile import load_profile
from bootstrap import get_clients, get_portfolio

st.title("AI Advisor")
st.warning(DISCLAIMER)

config, _, _, _ = get_clients()
ai_cfg = config.get("ai_advisor", {})
profile = load_profile(config)

df, _ = get_portfolio()
if df.empty:
    st.error("No holdings loaded — can't analyze the portfolio.")
    st.stop()

analysis = advisor_analysis.analyze(df, profile)

# ── Deterministic gap analysis (factual, no LLM) ─────────────────────────────

st.subheader("Allocation vs. your profile")
geo = analysis.geo
g1, g2, g3 = st.columns(3)
g1.metric(
    "US (by domicile)",
    f"{geo.us_pct:.1f}%",
    f"{geo.us_gap_pp:+.1f}pp vs target" if geo.us_gap_pp is not None else None,
)
g2.metric(
    "International",
    f"{geo.intl_pct:.1f}%",
    f"{geo.intl_gap_pp:+.1f}pp vs target" if geo.intl_gap_pp is not None else None,
)
g3.metric("NAV", f"${analysis.nav:,.0f}")
if geo.us_target_pct is not None:
    st.caption(
        f"Equity-sleeve targets (normalized): US {geo.us_target_pct:.0f}% / "
        f"International {geo.intl_target_pct:.0f}%. The dashboard sees your brokerage equity holdings only."
    )
else:
    st.caption("Set `investor_profile.target_allocation` to compare against a geographic target.")

if analysis.income is not None:
    inc = analysis.income
    i1, i2, i3 = st.columns(3)
    i1.metric("Dividend income (est.)", f"${inc.annual_income:,.0f}/yr")
    i2.metric("Portfolio yield", f"{inc.portfolio_yield_pct:.2f}%")
    if inc.income_target is not None:
        i3.metric(
            "vs income target",
            f"${inc.income_target:,.0f}",
            f"${-inc.income_gap:,.0f}" if inc.income_gap is not None else None,
            delta_color="normal",
        )

if analysis.concentration:
    st.subheader("Concentration")
    st.warning(f"Positions above your max single-position limit ({analysis.concentration[0].limit_pct:.0f}% of NAV):")
    st.dataframe(
        [{"Ticker": c.ticker, "Weight %": round(c.weight_pct, 1)} for c in analysis.concentration],
        width="stretch",
        hide_index=True,
    )

if analysis.sectors:
    st.subheader("Sector weights")
    flag_label = {"overweight_pref": "✓ preferred", "avoid_violation": "⚠ on avoid list", "": ""}
    st.dataframe(
        [
            {"Sector": s.sector, "Weight %": round(s.weight_pct, 1), "Note": flag_label.get(s.flag, "")}
            for s in analysis.sectors
        ],
        width="stretch",
        hide_index=True,
    )

# ── Claude narrative — EXPLICIT, opt-in (no LLM call on page load) ────────────
# Cost safeguards: (1) the call fires only when you click Generate — never on
# page load or navigation; (2) the result is keyed on a COARSE signature of the
# portfolio (NAV bucketed to ~$10k, allocations to ~1pp), so small price moves
# reuse the cached commentary instead of re-billing; (3) the result is cached in
# session state, so revisiting the page re-displays it with no new call.

st.subheader("AI commentary")
model = ai_cfg.get("model", advisor_llm.DEFAULT_MODEL)
posture = ai_cfg.get("posture", "educational")
max_tokens = int(ai_cfg.get("max_tokens", advisor_llm.DEFAULT_MAX_TOKENS))

sig = advisor_analysis.coarse_signature(analysis, model, posture)
cache = st.session_state.setdefault("_advisor_commentary", {})
commentary = cache.get(sig)

if st.button("↻ Regenerate" if commentary else "✨ Generate AI commentary"):
    with st.spinner("Generating AI commentary…"):
        try:
            commentary = cache[sig] = advisor_llm.generate_commentary(
                analysis, profile, model=model, posture=posture, max_tokens=max_tokens
            )
        except advisor_llm.AiAdvisorUnavailable as e:
            st.warning(f"AI commentary unavailable: {e}")
            st.stop()

if commentary is None:
    st.info(
        "No API call is made until you click **Generate**. The result is cached per "
        "portfolio state (NAV/allocations bucketed), so small price moves won't re-bill — "
        "use Regenerate to force a fresh call."
    )
else:
    st.markdown(commentary.narrative)
    if commentary.considerations:
        st.markdown("**Areas to consider**")
        for item in commentary.considerations:
            st.markdown(f"- {item}")
    st.caption(f"Generated by {model} · {posture} framing · informational only.")
